### ISSUE TITLE
GLIBC issue on Debian Bullseye

### ISSUE THREAD

**Issue by Darkle** [StarlaneStudios/Surrealist#10]
**Describe the bug**
Running surrealist on Debian Bullseye gives the following error: ```./surrealist: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34` not found (required by ./surrealist)```

I am able to build from source just fine though. 

Just thought i would mention the error in case building on debian is a possibility for you instead of Ubuntu (which i assume you are building on for the linux release) as a debian build should also work fine for Ubuntu.

Thanks for the app!

**Comment by macjuul** [comment]
This is currently a little difficult to change since it appears [GitHub only offers Ubuntu based images](https://github.com/actions/runner-images#available-images). I'm not as experienced with non-ubuntu distros so any further ideas or PRs to solve this would be appreciated!

**Comment by macjuul** [comment]
As of version 1.6 Surrealist is now distributed in the form of .deb and .AppImage files for Linux. I'm unsure of this fixes your issue however it may solve it
