### ISSUE TITLE
Start local locks the database

### ISSUE THREAD

**Issue by marko-lazic** [StarlaneStudios/Surrealist#105]
**Describe the bug**
I created a local file database using Rust surrealdb crate with kv-rocksdb feature enabled, opened the Surrealist app, and in Settings changed the Storage mode to File Storage and specified my Storage path. When I start the local database with Surrealist it locks my backend app from writing to the db.

My service log:
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Db(Tx("IO error: While lock file: /Users/.../db/my.db/LOCK: Resource temporarily unavailable"))'

**Expected behavior**
Might be that this is normal for a file database but I expected that other clients could write simultaneously.

**Environment (you can view the current version under Settings):**
 - Operating System: MacOS 
 - Surrealist Version: 1.9.0 
 - SurrealDB Version: 1.0.0-beta.9

**Comment by macjuul** [comment]
Just to confirm, you're starting the database once via Surrealist, but when you connect to it using the Rust crate it panics when you execute a query?

**Comment by marko-lazic** [comment]
Yes. It releases the lock by stopping the database via Stop local database button in Surrealist. Then the Rust crate can execute a query.

**Comment by macjuul** [comment]
Apologies for the late response. A single RocksDB database can only be used by one process at a time. When you launch SurrealDB using Surrealist this will lock the database.

What you want to do is connect to this database using `Surreal::new::<Ws>("address")` rather than `Surreal::new::<RocksDB>("path")`
