### ISSUE TITLE
Desktop app throws a "Failed to deserialize a binary response" error when processing decimal numbers

### ISSUE THREAD

**Issue by varmiral** [StarlaneStudios/Surrealist#110]
**Describe the bug**
This only happens in the desktop app. Tables containing float128 data don't open. Query fails with a `Failed to deserialize a binary response: Bincode does not support the serde::Deserializer::deserialize_any method` error.

**To Reproduce**
1. Execute the query `0.1dec + 0.2`
2. See error

**Expected behavior**
Result in the web app is `"0.3"` (as string?)

**Environment (you can view the current version under Settings):**
 - Operating System: Windows 10
 - Surrealist Version: 1.9.1
 - SurrealDB Version: 1.0.0+20230913.54aedcd

**Comment by macjuul** [comment]
This is likely related to [this issue](https://github.com/surrealdb/surrealdb/issues/2670)

I just released a new version of Surrealist which uses SurrealDB 1.0 internally, so as long as your database also runs 1.0 it should resolve the issue.
