### ISSUE TITLE
surrealist 1.9.2 designer view fully collapsed.

### ISSUE THREAD

**Issue by leefordjudes** [StarlaneStudios/Surrealist#111]
**Describe the bug**
A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.
![Screenshot 2023-09-20 192938](https://github.com/StarlaneStudios/Surrealist/assets/13608248/53e5274f-1537-49d2-ad8a-ba732e77d0c1)

**To Reproduce**
simply go to designer view

**Expected behavior**
 as like in previous versions

**Environment (you can view the current version under Settings):**
 - Operating System [e.g. Windows]: 11
 - Surrealist Version [e.g. 1.2.0]: 1.9.2
 - SurrealDB Version [execute "surreal version"]: v1.0.0

**Comment by macjuul** [comment]
I'll place limits on the table to prevent the UI from breaking in such a way. For now, if you press the cog icon on the top right of the table graph panel you can set table appearance to *simple* or *summary* for a cleaner overview.

![image](https://github.com/StarlaneStudios/Surrealist/assets/7606171/4cc2bfa3-53e2-4503-846d-281f2cd6b2b7)

**Comment by macjuul** [comment]
Additionally, the next release will further improve the Designer UI to limit the amount of table fields, with the option to expand if desired. Additionally the text rendering has also been improved.

![image](https://github.com/StarlaneStudios/Surrealist/assets/7606171/358952c6-9065-48f4-9a60-a2dd700d15ad)
