### ISSUE TITLE
Query timeout after 10s despite of TIMEOUT statement

### ISSUE THREAD

**Issue by TudorAndrei-Pythia** [StarlaneStudios/Surrealist#112]
**Describe the bug**
The surrealist interface doesn't respect the timeout statement.

**To Reproduce**
Run long query and include `TIMEOUT 20s`

**Expected behavior**
I ran the query from the CLI and the duration was 18s.

**Environment (you can view the current version under Settings):**
 - Operating System: Linux
 - Surrealist Version: 1.9.2
 - SurrealDB Version: 1.0.0+20230913.54aedcd for linux on x86_64

**Comment by macjuul** [comment]
Surrealist handles timeouts externally from SurrealDB. If this conflicts with your use case you can increase the timeout to any value you want in the settings under the Connection tab. Hope this helps!
