### ISSUE TITLE
Statements With Only keyword returns an array, must return an object

### ISSUE THREAD

**Issue by leefordjudes** [StarlaneStudios/Surrealist#114]
**Describe the bug**
Select With Only keyword returns array of result in app, but in browser it returns exact result as object

**To Reproduce**
```sql
create only test:1 content {name:"abc"};
select * from only test:1;
select * from only [1,2,3] where $this = 1;
```

When Running in surrealist app:
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/ed535b73-f6e4-4339-a770-1ef68c269de8)

When Running in browser, url https://surrealist.app, this is correct result
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/b0525c4d-f488-4069-afd6-9a2dcc7db589)

**Expected behavior**
when statement uses only keyword, then the result must be an object, not an array.

**Environment (you can view the current version under Settings):**
 - Operating System [e.g. Windows]: 10
 - Surrealist Version [e.g. 1.2.0]: 1.9.2
 - SurrealDB Version [execute "surreal version"]: 1.0.0

**Comment by macjuul** [comment]
Related to #115
