### ISSUE TITLE
Could not connect surrealdb using network ips, but 1.9.2 can connect db using network ips [Surrealist 1.10 + web]

### ISSUE THREAD

**Issue by leefordjudes** [StarlaneStudios/Surrealist#117]
**Describe the bug**
Surrealist 1.10 Could not connect surrealdb using network ip, but 1.9.2 can connect db using network ip

**To Reproduce**
surrealist 1.10
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/79fcd7ce-e46f-455b-b002-219516f7517d)

surrealist 1.9.2 
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/40868883-6ea6-41a4-a88f-459a3c55b6c2)

**Expected behavior**
should connect surreal db through network ip using surrealist 1.10 and also surrealist from web

**Environment (you can view the current version under Settings):**
 - Operating System [e.g. Windows]: 11
 - Surrealist Version [e.g. 1.2.0]: 1.10
 - SurrealDB Version [execute "surreal version"]: 1.0.0

**Comment by macjuul** [comment]
Could you open dev tools using `Ctrl + Shift + I` and check the console tab for any potential error messages? Additionally, are you able to connect using the `surreal sql` command using surrealdb 1.0 and the same ip?

**Comment by leefordjudes** [comment]
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/03b85600-904a-4133-b2b5-11b5dd003fdd)

yes, there is some errors in console

**Comment by macjuul** [comment]
This is happening because the connections have been moved to WebAssembly, I'll see if I can find a solution for this. The binary messages are due to SurrealDB using a new binary WebSocket protocol.

**Comment by macjuul** [comment]
I pushed a possible fix to the main branch, however I do not have the time to test this myself. If possible, try and build the main branch from source to see if it works for you, however it's alright if this isn't possible.

**Comment by leefordjudes** [comment]
yes, its worked in local build
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/79db73c6-02bd-405c-9170-ea411b020164)

**Comment by macjuul** [comment]
Awesome, thanks for testing it!
