### ISSUE TITLE
Combined view result panel not display all results in all time. if first #result1 returns null or empty array then combined view shows nothing

### ISSUE THREAD

**Issue by leefordjudes** [StarlaneStudios/Surrealist#118]
**Describe the bug**
Combined Result panel not display #result2,.. On First time, if first #result1 returns null or empty array,
and after that if go arround other result views, that is, go to json view and select each json result and then go to table view, 
after that goto first result view "combined view", at that time it shows all results.

**To Reproduce**
```sql
let $a = [1,2,3];
select * from $a;
select * from [1,2,3];
```
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/5ea6c6cb-7988-44ec-ad39-a5b085bc4e0b)
then go arround json view, and switch some result page which contain some result, here i go to result#2 page
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/9d548045-7972-4b7c-a824-d1e830ee523d)
then go to combined view, now you will get all result
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/06de85e0-2bb8-482b-ad76-a2adb7d35457)

**Expected behavior**
all time, all results must shown in combined view.

and check it with valid table datas. some time table view also not showned result.

**Environment (you can view the current version under Settings):**
 - Operating System [e.g. Windows]: 11
 - Surrealist Version [e.g. 1.2.0]: 1.0
 - SurrealDB Version [execute "surreal version"]: 1.10

**Comment by macjuul** [comment]
Issue has been fixed and will be included in the next release :)
