### ISSUE TITLE
Incorrect surrealQL editor modal size modal size

### ISSUE THREAD

**Issue by hysuki** [StarlaneStudios/Surrealist#119]
**Describe the bug**
SurrealQL Editor modal size seems to have been specified incorrectly.

<img width="1465" alt="스크린샷 2023-09-26 오후 6 30 31" src="https://github.com/StarlaneStudios/Surrealist/assets/35303552/64e9ebf7-a77e-4019-b9b4-0e05ca426b39">

**To Reproduce**
1. Go to 'Designer'
2. Click on 'table'
3. Click on 'permissions edit icon'

**Expected behavior**

**Environment (you can view the current version under Settings):**
 - Operating System [e.g. Windows]: macOS Ventura 13.5.2
 - Surrealist Version [e.g. 1.2.0]: 1.10.0
 - SurrealDB Version [execute "surreal version"]: 1.0.0+20230913.54aedcd for linux on aarch64

**Comment by macjuul** [comment]
Fixed in the next release
