### ISSUE TITLE
Improve UX in `saved queries` functionality

### ISSUE THREAD

**Issue by oskar-gmerek** [StarlaneStudios/Surrealist#12]
**Describe your feature request**

I think there is a field for improving user experience in saved queries functionality.
I currently use `PostmanCanary` and would like to fully switch to Surrealist, but there are a few things that make my life easier with Postman than Surrealist that stop me from swapping it.

1. **Moving parts of UI**
There is currently a little menu in saved queries with `remove`, `copy`, `edit`, and `run query` buttons. This menu is hidden by default and shows on hover which unfortunately comes to be very annoying as it is 'moving' all other queries in that section.  Especially when are a lot of saved queries.

2. **Transition**
The same menu (see 1.) has a transition on hover. It's invisible if your cursor is away. So if you want to run the saved query, you need to move the cursor on the query itself, wait a few ms, and move it to the `run query` button. It's one unnecessary step. Like the previous issue, it's going worst as you more often use this functionality. Especially when you have a lot of similar and long queries saved.

3. **Conciseness**
I think only query names should be visible in the list of saved queries. Of course, the best solution will be to leave this to the end user and just allow them to define it in the settings. I have a 30' display and in Surrealist I can see only 6 queries at once vs 40 queries in Postman.

4. **Opening of cards**
I believe the best way to handle saved queries will be to open the card with a specific query after clicking on it. Currently, we can only: copy, remove or run the query, but if the query is a long one we can't see what we actually copying, removing, or running. The edit functionality is bugged ( #13 ) making it unusable in some cases or at least not a nice experience. This will be a nice if opened tab will be named based on the saved query.

**Comment by macjuul** [comment]
Thanks for your detailed feedback! I agree with your points and believe the UI can definitely be improved upon. I'll spend some time redesigning it in the near future taking your points into account.

Just for clarification, when you mention under your fourth point `I believe the best way to handle saved queries will be to open the card with a specific query after clicking on it`, are you suggesting replacing the hover expansion with a click toggle instead?

**Comment by oskar-gmerek** [comment]
@macjuu

No, I probably mismatched `card` with `tab` here.

I think clicking on the saved queries list items should trigger the opening of a new tab with saved content. 
This hover menu will be better to change with the context menu (right mouse click).

**Comment by macjuul** [comment]
The saved queries UI has been reworked recently to align with some of your points stated above so I'll close this issue as completed
