### ISSUE TITLE
Highlight Keyword "FIELDS" in grammar while creating Index, but "COLUMNS" is already highlighted 

### ISSUE THREAD

**Issue by leefordjudes** [StarlaneStudios/Surrealist#121]
**Describe the bug**
Highlight Keyword "FIELDS" in grammar while creating Index, but "COLUMNS" is already highlighted 

**To Reproduce**
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/44d9fd44-2c2f-480b-9624-0602abd0f1d9)

**Expected behavior**
Keyword "FIELDS" must be highlighted

**Environment (you can view the current version under Settings):**
 - Operating System [e.g. Windows]: 11
 - Surrealist Version [e.g. 1.2.0]: 1.10
 - SurrealDB Version [execute "surreal version"]: 1.0.0

**Comment by macjuul** [comment]
Fixed in the latest grammar
