### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by Heartnett** [StarlaneStudios/Surrealist#124]
**Describe your feature request**
Self-host Surrealist in a docker container.  

**Are you willing to contribute this feature?**
No.

**Related pull request (if applicable)**
N/A.

**Comment by Pixelycia** [comment]
Application has some issues with desktop application, but if you will access to your database hosted on docker via their web application https://surrealist.app/ - everything is working as expected

**Comment by Heartnett** [comment]
> If you will access to your database hosted on docker via their web application https://surrealist.app/ - everything is working as expected, I think you're trying to "run" database though the button in UI instead of "Send Query".
> 
> And just in case - https://hub.docker.com/r/surrealdb/surrealdb

The requirement is to **self-host** the **surrealist app** as a **docker container** locally.

Not the use of an existing deployed instance that's hosted elsewhere, or the desktop app.

**Comment by Heartnett** [comment]
> ... I read it wrong because request itself quite odd and cover rare cases.....

I'm not sure how this request is "quite odd", but OK. Maybe it was the way I worded the feature request?

Its rather common place to containerize applications, web based (client) apps too for that matter.

Its also common place to people to find other (quicker) means of installing apps without having to waste time manually installing (and potentially configuring) dependencies (don't matter how many) and/or dealing with version conflicts, clean-ups etc. But I guess sometimes people never consider these scenarios and are therefore classified as "rare cases"?

**Comment by Pixelycia** [comment]
I agree, but anyway I do not think this is a super important feature to maintain and support for serverless client application. If it important to you and you think it might be important for others - then do a contribution to the project you're using for free.

**Comment by Heartnett** [comment]
> I agree, but anyway I still don't think this is a super important feature to maintain and support for serverless client application - it's too much effort for a feature that going to be used by couple of people in total. If it important to you and you think it might be important for others - then do a contribution to the project you're using for free.

Thanks for your time.

**Comment by coutouly** [comment]
it should be great

**Comment by 0xorial** [comment]
I have a surrealdb running on my local server and it would be great if I could use surrealist to access it. From the discussion above I could not figure out if that scenario is supported via surrealist.app or I have to build my own docker image (which would be rather inconvenient tbh). I tried accessing my db from surrealist app using my local server address, but it does not work on any protocols, always giving "GET https://***:8001/version net::ERR_SSL_PROTOCOL_ERROR" in console. Could anyone clarify if such scenario is supported or refer me to some kind of docs/discussions about it ?
