### ISSUE TITLE
Variable details can not be retrieved, if variable value is record id,

### ISSUE THREAD

**Issue by leefordjudes** [StarlaneStudios/Surrealist#126]
**Describe the bug**
Variable details can not be retrieved, if variable value is record,

**To Reproduce**
1. use the following queries, and variables
```json
{
    "man1":"manufacturer:man1"
}
```
```sql
insert into manufacturer [
    {
        "id":"manufacturer:man1",
        "name":"man1",
        "product":"Amoxicillin"
    },
    {
        "id":"manufacturer:man2",
        "name":"man2",
        "product":"Diclofenac"
    },
    {
        "id":"manufacturer:man3",
        "name":"man3",
        "product":"Metoprolol"
    }
];

select name, product from "manufacturer:man1";

select name, product from $man1;
```
The first two queries work, 3rd query returns null.
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/00d5dac2-d122-4071-ae63-9e0af98c8b3c)

**Expected behavior**
the query must return the result, when the variable value is a record id, 

**Environment (you can view the current version under Settings):**
 - Operating System [e.g. Windows]: 11
 - Surrealist Version [e.g. 1.2.0]: 1.10.1
 - SurrealDB Version [execute "surreal version"]: 1.0.0

**Comment by koakh** [comment]
same here, variables seem not work in my latest version

I recompile surrealist right now with current code from this repository and now it works flawless :)
Version 1.10.1 by Starlane Studios

you can rebuild or download latest version

and try with a simple query only with variable

`$user`

and 

add in variables

`{ "user": "koakh" }`

result will be

`[   "koakh"  ]`

in the past here we don't have any result

this app is awesome, I love it

**Comment by leefordjudes** [comment]
still, it is not resolved. **variables returns null if it is a record id**
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/34398c51-019e-4242-b26a-72a7379cac44)

**Comment by koakh** [comment]
I confirm variables returns null if it is a record id

even when query `$man1;` returns `[ "manufacturer:man1" ]

![image](https://github.com/StarlaneStudios/Surrealist/assets/6191096/0e23237b-b5dd-4222-b044-4045ab4710b5)
