### ISSUE TITLE
Surrealist 1.10.1 - App crashes often and shows a black or white screen,

### ISSUE THREAD

**Issue by leefordjudes** [StarlaneStudios/Surrealist#127]
**Describe the bug**
App crashes often and shows a black or white screen,

**To Reproduce**
while working, the surrealist app crashed often, but I didn't get the correct situation.
![surrealist-err](https://github.com/StarlaneStudios/Surrealist/assets/13608248/98c2614f-42d0-42c1-ab63-e7b3d877b31c)

**Expected behavior**
The app should not be crashed.

**Environment (you can view the current version under Settings):**
 - Operating System [e.g. Windows]: 11
 - Surrealist Version [e.g. 1.2.0]: 1.10.1
 - SurrealDB Version [execute "surreal version"]: 1.0.0

**Comment by mghase** [comment]
am geting the white screen. any solution please

**Comment by leefordjudes** [comment]
kindly resolve this, frequently black screen comes and the app hangs.

**Comment by leefordjudes** [comment]
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/a561efe3-bf6f-4829-a324-ad165afb528c)

**Comment by macjuul** [comment]
This issue has been traced to a bug in SurrealDB so I can't make a fix right now myself. It would help tremendously if you can send your config with any sensitive information such as passwords stripped out. It might help us find a solution quicker.

You can find the config file here
- Linux: `$XDG_CONFIG_HOME` or `$HOME/.config/surrealist.json`
- MacOS: `$HOME/Library/Application Support/surrealist.json`
- Windows: `%AppData%\surrealist.json`

**Comment by leefordjudes** [comment]
Okay, now I have reinstalled my system, it will come after a few weeks of usage, so when it comes, I will update this issue.

**Comment by leefordjudes** [comment]
Bro, our company discontinued using surrealdb due to its low performance, indexing issues, and many related functionality issues, we moved to Postgres, and after some years(surrealdb fixed its performance), we will give back.
Until then, continue the journey...
