### ISSUE TITLE
Icon wrapping in record explorer pane

### ISSUE THREAD

**Issue by ntorrey** [StarlaneStudios/Surrealist#129]
**Describe the bug**
When the width of the Record Explorer pane is narrow, the icons in the upper right wrap around which breaks the UI.
![2023-10-08 10 39 39](https://github.com/StarlaneStudios/Surrealist/assets/56656692/e48f1581-36b9-43e9-8f98-51c0d573d5a1)

**To Reproduce**
Shrink the width of the window until the buttons in the upper right of the Record Explorer wrap.

**Expected behavior**
Maybe add an ellipsis if the icons overflow the container.

**Environment:**
 - Operating System: Windows
 - Surrealist Version: 1.10.1 
 - SurrealDB Version: surrealdb-1.0.0+20230922.a0072cf

Thanks again!

**Comment by macjuul** [comment]
Will be fixed in the next release
