### ISSUE TITLE
Need a way to Hide any panel ["Result", "Query", "Variables"]

### ISSUE THREAD

**Issue by leefordjudes** [StarlaneStudios/Surrealist#130]
**Describe your feature request**
Sometime i am working only query window with the long line, at that time i cannot shrink all result panel, and variables panel,
and sometime i wish to see all results in a full window or want to view my input json variables,
all that time some unused panels takes some places, 
so it is possible add a way to hide any panel ["Result", "Query", "Variables"] like toggle console.

**Are you willing to contribute this feature?**
No bro, i don't know react. i wish to contribute as a tester.

**Related pull request (if applicable)**

**Comment by esakkimuthu-p** [comment]
This is very useful. Kindly implement it.
