### ISSUE TITLE
Explore only showing 1 page when more than one page should be available

### ISSUE THREAD

**Issue by joshward** [StarlaneStudios/Surrealist#133]
**Describe the bug**
In the explore panel the pagination says 1 of 1 pages even though there are more than one page worth of data. Trying to manually enter the next page doesn't work nor does clicking on the next page button. Change the page count does show more data but still only shows 1 of 1 page.

![image](https://github.com/StarlaneStudios/Surrealist/assets/11366954/18c1e0a9-417d-4559-bdb6-223a111e46d7)

The row count does seem to be correct
![image](https://github.com/StarlaneStudios/Surrealist/assets/11366954/5f89c55e-eed2-4806-98e6-148fd88f35b3)

I did see that it was working in a previous version right before I upgraded to the latest.

**To Reproduce**
1. Go to Explore 
2. Set page count to less than table size
4. See that only one page is available and can't change pages

**Expected behavior**
Should have the correct number of pages and the ability to change pages.

**Environment (you can view the current version under Settings):**
 - Operating System:  Windows 11
 - Surrealist Version: 1.10.3
 - SurrealDB Version: 1.0.0+20230913.54aedcd for windows on x86_64

**Comment by macjuul** [comment]
Will be fixed in the next release
