### ISSUE TITLE
Graph view doesn't work with edges defined outside of Surrealist.

### ISSUE THREAD

**Issue by TudorAndrei** [StarlaneStudios/Surrealist#134]
**Describe the bug**
If I create my edges only using the relate keyword. Then, in the designer view the edges are seen as tables. 

**To Reproduce**
create relationship without defining edge
```sql
relate person:1->talks->person:2
```
**Expected behavior**
Create an 'edge' table, not a 'node' table.

**Environment (you can view the current version under Settings):**
 - Operating System [e.g. Windows]: linux
 - Surrealist Version [e.g. 1.2.0]: Version 1.10.3
 - SurrealDB Version [execute "surreal version"]: v1

**Comment by macjuul** [comment]
This is expected. Surrealist determines edge tables based on the presence of an `in` and `out` field in the schema. When creating an edge table in Surrealist this is automatically defined, however you can do it manually as well.

**Comment by TudorAndrei** [comment]
So I order to fix this,  I should define the edge tables with the in, out fields?

**Comment by macjuul** [comment]
That's correct!
