### ISSUE TITLE
Error: failed to find unused port

### ISSUE THREAD

**Issue by jaco-codexorbis** [StarlaneStudios/Surrealist#137]
**Describe the bug**
Run surrealist after update fails with error: failed to find unused port.

**To Reproduce**
Uninstall previous revision and removed configuration files. Install new version and run from terminal.

**Expected behavior**
Application starts and is usable.

**Environment (you can view the current version under Settings):**
 - Operating System: Ubuntu 22.04
 - Surrealist Version: 1.11.0 (first appreared in 1.10.1)
 - SurrealDB Version: 1.0.0+20230913.54aedcd for linux on x86_64

**See attached stack trace**
[surrealist_v1-11.txt](https://github.com/StarlaneStudios/Surrealist/files/13187362/surrealist_v1-11.txt)

**Comments**
- IPV6 is disabled in the kernel on the workstation.
- Rolling back to v1.10 works

**Comment by macjuul** [comment]
I have implemented a fallback port when automatic port detection fails, however I cannot guarantee this solves the issue entirely. If similar issues persist in the next release feel free to open a new issue!
