### ISSUE TITLE
Help Need: How to connect surrealdb(local/network) using surrealist.app from brave browser.

### ISSUE THREAD

**Issue by leefordjudes** [StarlaneStudios/Surrealist#140]
Help Need: How to connect surrealdb(local/network) using surrealist.app from brave browser.
Now its not connected to my local surreal db.

![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/c06af6fb-aded-405b-ae1e-eecfcf382f2e)

kindly help:

is there any extra settings to do in brave browser something like in stackblitz to open in brave browser

**Comment by macjuul** [comment]
Connections to localhost are disallowed by some browsers due to security reasons. I have experienced chromium based browsers including Brave displaying this behavior, although Firefox does appear to allow it.

Unfortunately this isn't something I can fix because it is out of my control.
