### ISSUE TITLE
Error unexpected argument '--auth' after update Surrealist and SurrealDB

### ISSUE THREAD

**Issue by og-dev** [StarlaneStudios/Surrealist#152]
After update from `Surrealist 1.7.0` with `SurrealDB  v1.0.0-beta.9+20230402`
to `Surrealist 1.11` with `SurrealDB 1.0.0` I am getting this error:

```
**Failed to start database**
SurrealDB did not start correctly, check the console for more information
```

```
CONSOLE

error: Found argument '--auth' which wasn't expected, or isn't valid in this context
If you tried to supply `--auth` as a value rather than a flag, use `-- --auth`
```
Inspector console:
```
query
Runner: Received database start signal     index-1849a2c6.js:114

query   index-1849a2c6.js:117 
Connecting to 127.0.0.1:9900   index-1849a2c6.js:117 
WebSocket connection to 'ws://127.0.0.1:9900/rpc' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
(anonymous) @ index-1849a2c6.js:117
```
The WS error is due to the server is not running, because it is not possible to start it from surrealist.
I'm using 9900 port to run surrealdb

Server can be started manually, but from surrealist [ start local database button ]
Before update, all was working without issues. 

OS: Windows 7
In this machine I'm using others Rust, Tauri projects fine.

Is there a way to fix this issue?
I'll appreciate any help that you can provide

**Comment by macjuul** [comment]
Surrealist passes the `--auth` flag when launching a SurrealDB instance, however this flag was added after beta 9. The only solution is to use a newer version of SurrealDB (v1.0.0 is recommended)
