### ISSUE TITLE
Query execution in Combined view shows only the first query time.

### ISSUE THREAD

**Issue by TudorAndrei** [StarlaneStudios/Surrealist#157]
**Describe the bug**
In query mode, when running two queries, the combined view shows only the time of the first query.

**To Reproduce**
- Go to query mode
- Run two queries at the same time.
- Alternate between JSON view and combined view and check the time

**Expected behavior**
The combined view should show the total execution time.

**Environment (you can view the current version under Settings):**
 - Operating System [e.g. Windows]: Linux
 - Surrealist Version [e.g. 1.2.0]: 1.11
 - SurrealDB Version [execute "surreal version"]: v1

**Comment by macjuul** [comment]
This has been fixed and will be available in the next release
