### ISSUE TITLE
Zoom in for UI

### ISSUE THREAD

**Issue by IgnisDa** [StarlaneStudios/Surrealist#16]
**Describe your feature request**
It would be nice if I were able to zoom in to the UI, some elements feel too small. Standard buttons like <kbd>ctrl +</kbd>, <kbd>ctrl -</kbd> do not work. There is no related setting as well.

**Are you willing to contribute this feature?**
No, I do not have experience with the tech stack used.

**Related pull request (if applicable)**
N/A

**Comment by IgnisDa** [comment]
@macjuul Thank you for the quick fix. Could you please release it to github releases?

**Comment by macjuul** [comment]
It'll be available in the next release I plan on releasing later today together with some other improvements 🙂
