### ISSUE TITLE
Unable to view created tables and query database

### ISSUE THREAD

**Issue by dodanex** [StarlaneStudios/Surrealist#163]
**Describe the bug**
Unable to view created tables in Designer;
Unable to query data in Query, the result is: `Failed to deserialize a binary response: invalid value: integer `54`, expected variant index 0 <= i < 2`

**To Reproduce**
1. create some tables in Designer
2. you will see it's not appearing in the interface
3. if you connect to the database with Postman and get info for db you will see the tables exists
4. use postman to create data then try to query it, will not work

**Expected behavior**
Expecting to show the tables and the data queried.

**Environment (you can view the current version under Settings):**
 - Operating System [e.g. Windows]: 11 x64 Pro
 - Surrealist Version [e.g. 1.2.0]: 1.11.1-nightly.1
 - SurrealDB Version [execute "surreal version"]: 1.1.0 Beta 3

**Comment by AlbertMarashi** [comment]
Also getting this issue on **MacOS** using Surreal-v1.0.2

**Comment by macjuul** [comment]
I'm aware of conflicts and confusion surrounding which version of Surrealist is compatible with which version of SurrealDB, especially due to a recent error in the protocol. I intend on releasing a new version later this week in an attempt to clarify and solve some of these issues!

**Comment by AlbertMarashi** [comment]
Thank you @macjuul  and will this also work with 1.1.0?

**Comment by macjuul** [comment]
> Thank you @macjuul and will this also work with 1.1.0?

These issues will definitively be resolved with the 1.1.0 full release, however due to a versioning error in SurrealDB it will likely not work with the current betas

**Comment by AlbertMarashi** [comment]
@macjuul are you sure? I upgraded to the 1.1.0 that came out today but still had the issue unfortunately

**Comment by macjuul** [comment]
> @macjuul are you sure? I upgraded to the 1.1.0 that came out today but still had the issue unfortunately

I'll still have to make a new release of Surrealist. I'll aim to do so tomorrow if time allows it!

**Comment by MichielHegemans** [comment]
I have a similar issue when I create a `SCHEMAFULL` table which has a field of type array.

The web client shows this error in the console:
```
Uncaught (in promise) Parse error: Failed to parse query at line 1 column 51 expected one of FLEX(IBLE), TYPE, VALUE, ASSERT, DEFAULT, or COMMENT
  |
1 | DEFINE FIELD attributes[*] ON listing TYPE record PERMISSIONS FULL
  | 
```

This is the design of the table:
```
DEFINE TABLE listing SCHEMAFULL;

DEFINE FIELD title ON listing TYPE string;
DEFINE FIELD attributes ON listing TYPE array;
DEFINE FIELD attributes.* ON listing TYPE record;
```

Following from https://docs.surrealdb.com/docs/surrealql/statements/define/field#array-type this guide.

**Comment by macjuul** [comment]
Closing issue as this will be fixed in the next release

**Comment by AlbertMarashi** [comment]
@macjuul any ETA?

**Comment by macjuul** [comment]
Hopefully within the next few hours :)

**Comment by kearfy** [comment]
@MichielHegemans @macjuul linking https://github.com/surrealdb/surrealdb/issues/3217 for reference

**Comment by macjuul** [comment]
[Version 1.11.2](https://github.com/StarlaneStudios/Surrealist/releases/tag/v1.11.2) for SurrealDB 1.1 is now available
