### ISSUE TITLE
Design panel not updating when switching between designer tables

### ISSUE THREAD

**Issue by macjuul** [StarlaneStudios/Surrealist#166]
**Describe the bug**
The design panel does not update correctly when switching between tables. Alternatively, switching could be blocked until active changes are reverted or saved.

**Expected behavior**
You can either switch tables correctly, or the user is prompted to save/revert

**Comment by lthoerner** [comment]
I am experiencing this issue and it make the Designer feature unusable. If there is any priority system for bugs I would greatly appreciate it being escalated.

**Comment by lthoerner** [comment]
Thank you @macjuul! I'll try out the new build.
