### ISSUE TITLE
Unable to rename tables

### ISSUE THREAD

**Issue by dodanex** [StarlaneStudios/Surrealist#172]
**Describe the bug**
There is no way to rename a table after that table has been created from Designer tab.

**To Reproduce**
- Create a table in Designer tab
- Select the table and try to rename it

**Expected behavior**
Renaming a table is a must have feature.

**Environment (you can view the current version under Settings):**
 - Operating System [e.g. Windows]: w11 Pro
 - Surrealist Version [e.g. 1.2.0]: 1.11.3
 - SurrealDB Version [execute "surreal version"]: 1.1.1

**Comment by macjuul** [comment]
Unfortunately table renaming isn't supported by SurrealDB currently hence this functionality is missing in Surrealist.

I'll continue to consider implementing this behavior in some capacity with or without direct support in SurrealDB.

Thanks!
