### ISSUE TITLE
install the app in Apple M1 Pro

### ISSUE THREAD

**Issue by TN19Nworking** [StarlaneStudios/Surrealist#176]
I get this:
<img width="242" alt="Screenshot 2024-02-05 at 10 19 27 AM" src="https://github.com/StarlaneStudios/Surrealist/assets/159009370/fabd83bd-7b76-450d-880b-5a5033f6d5a9">

**Comment by ItsMateo** [comment]
Hi there! Kindly refer to the "Running on MacOS" section of the README, as it provides information on how to solve this exact issue.
