### ISSUE TITLE
crash and cant restart

### ISSUE THREAD

**Issue by coutouly** [StarlaneStudios/Surrealist#180]
**Describe the bug**
the surrealist crash 
i try to restart it after killing it even after a reboot a reinstal i get this
![image](https://github.com/StarlaneStudios/Surrealist/assets/7043117/d2f57220-cf58-46c9-ba99-fd6b7eb07181)

**To Reproduce**
index a table

**Expected behavior**
stop working

**Environment (you can view the current version under Settings):**
 - Operating System arch linux
 - Surrealist Version 1.11.4-1
 - SurrealDB Version [execute "surreal version"]: 1.2.1 for linux on x86_64

**Comment by macjuul** [comment]
This issue should now be resolved in [version 1.11.5](https://github.com/StarlaneStudios/Surrealist/releases/tag/v1.11.5)
