### ISSUE TITLE
ERROR surreal::cli: Couldn't open the specified file: Address already in use (os error 98)

### ISSUE THREAD

**Issue by micisse** [StarlaneStudios/Surrealist#185]
**Describe the bug**
Hello, to use Surrealist, I already have a server running from a terminal. In one of the previous versions, this wasn't a problem, but since the update, it's impossible to connect Surrealist to the server launched from the terminal. In the new version, Surrealist creates a new server and creates a PORT conflict. Is it possible to use Surrealist with a server external to the app?

![Capture d’écran_2024-03-19_18-18-33](https://github.com/StarlaneStudios/Surrealist/assets/56940294/82700ad9-41b8-49e9-828e-e6e003dd2d68)

P.S: I usually use the terminal for most of my db actions, and Surrealist is useful for a simpler quick view in my case and this context.

---

Sorry, but I'll take this opportunity to leave these ideas here (perhaps with a few changes/suggestions) in the block that follows.

* Settings (Local Database) seem to be global and not specific to each environment. A single Storage mode, a single storage path, although it is possible to use "surrealbin ... --bind <IP>" in terminal. You can have several addresses, each with a different storage mode and/or storage path.
![Capture d’écran_2024-03-19_19-07-39](https://github.com/StarlaneStudios/Surrealist/assets/56940294/3add71dd-179c-46f9-967e-3e9c73570d6b)
![Capture d’écran_2024-03-19_18-45-50](https://github.com/StarlaneStudios/Surrealist/assets/56940294/09c109a0-3b2f-41d3-acd8-c68843af1a4e)

> Perhaps the app is designed to handle only one instance for now

---

**To Reproduce**
1. Start server on terminal with `surreal start --allow-all -u root -p root file:///<file_path>` (I use file, not memory)
2. Try to connect Surrealist to localhost:8000
4. See error in console
![Capture d’écran_2024-03-19_18-18-49](https://github.com/StarlaneStudios/Surrealist/assets/56940294/08789785-8600-4eb9-8f04-39a34064f74d)

**Expected behavior**
Surrealist must also be able to connect to an existing server, not create a new one (Note that I don't remember experiencing this type of problem with previous versions until I did the new updates).

**Environment (you can view the current version under Settings):**
 - Operating System [e.g. Windows]: Linux 
 - Surrealist Version [e.g. 1.2.0]: 1.11.6
 - SurrealDB Version [execute "surreal version"]: 1.3.1

**Comment by macjuul** [comment]
The start and console buttons in the top right of the interface will spin up a server in the same way you would do via the terminal. It exists as an easy way to launch a localhost SurrealDB instance without having to use the terminal, and is separate from the concept of connecting.

Because of this you should avoid launching SurrealDB from the interface and terminal at the same time, as it could indeed try binding to the same port and fail. When you are running SurrealDB from the terminal, you should be able to connect to it from Surrealist just like you would when launching it from the interface

**Comment by micisse** [comment]
@macjuul  Thanks for the start and play button.

For the connection to the server, maybe I'm doing it wrong or there's a bug but I can't connect Surrealist to the server as root or anonymous. But I can access the contents of the database via sql surrealdb sql --conn "http://localhost:8000". See video


https://github.com/StarlaneStudios/Surrealist/assets/56940294/b408e5a6-a042-4138-baac-d3664bdc4f60

**Comment by micisse** [comment]
@macjuul I've downgraded to surrealdb version 1.0.0, compatible with Surrealist 1.10.3, and all is well 🙃
