### ISSUE TITLE
Can't access the documentation, broken link

### ISSUE THREAD

**Issue by wildwestrom** [StarlaneStudios/Surrealist#186]
On the Readme, it says you can read the documentation at https://surrealist.starlane.studio/, but the link leads to nothing. Is the site down? Is there an alternative site? What's going on?

**Comment by macjuul** [comment]
The old docs are indeed offline as I am working on new documentation. The original site did not contain much more than the GitHub README contents, so for now it's best to read that to get a basic understanding of the app

**Comment by wildwestrom** [comment]
Ah ok, well that settles that then. I'll close this for you.
