### ISSUE TITLE
Database imports seem not to be working

### ISSUE THREAD

**Issue by AlbertMarashi** [StarlaneStudios/Surrealist#187]
**Describe the bug**
A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.

- Using the download schema works correctly and creates a `.surql` file
- Uploading the schema does not create the necessary tables as specified in `.surql`

May be related to https://github.com/surrealdb/surrealdb/issues/3548

**Comment by AlbertMarashi** [comment]
Running the script via terminal works correctly, but only when using the HTTP endpoint setting

`surreal import --namespace app --database foo -u root -p root --endpoint http://localhost:8000 database.surql`

**Comment by macjuul** [comment]
The import functionality in Surrealist simply executes the statements found in a .surql file so it should be unaffected by such restrictions. You could open the devtools (`Command + Option + i`) and see if there are any errors logged in the console

**Comment by AlbertMarashi** [comment]
Was running an older version without realsing
