### ISSUE TITLE
What version of surrealist does SurrealDB use?

### ISSUE THREAD

**Issue by AlbertMarashi** [StarlaneStudios/Surrealist#188]
Sorry I wasn't sure how else to ask, but my Surrealist is running Surreal 1.0.2.

Is it compatible with other versions? I know I can update the executable path, but can you explain a bit more about this?

**Comment by AlbertMarashi** [comment]
I updated my executable path to `1.3.1` version and seems to be working fine, but out of curiosity, why is surrealist not using the latest database version?

**Comment by macjuul** [comment]
Surrealist embeds the SurrealDB rust crate for various tasks including connecting to the database and extracting information. This is entirely separate from the executable path in settings, as this is used by the database serving functionality which starts a SurrealDB server locally to connect to. 

The version used internally is fixed and currently needs to be bumped each time, however the executable path could still point to different versions. I still recommended where possible to use the version of Surrealist for the version of SurrealDB it is intended for as described at the bottom of the release notes on GitHub for maximum compatibility
