### ISSUE TITLE
Graph view for relations

### ISSUE THREAD

**Issue by bibaswan-bhawal** [StarlaneStudios/Surrealist#22]
**Describe your feature request**
Firstly thank you for creating this amazing tool. 

Given that SurrealDB is is capable of creating relations between records I think having visualization of these relations as a node graph would really help in being able to see the data.

**Are you willing to contribute this feature?**
Optionally, I am still getting used to SurrealDB and working on my own project in which I plan to have a sort of graph view for a users connections. If I am able to get that working I think it could be generalized to for surrealist as well.

**Related pull request (if applicable)**
e.g. PR #4

**Comment by macjuul** [comment]
Hello! I actually developed an experimental graph visualization view recently but decided to shelve it as I was not pleased with the result.

Since a database can contain vast amounts of records it easily becomes a difficult task visualizing these.

Here is an example of what it looked like
![image-4](https://user-images.githubusercontent.com/7606171/218609109-dd46fd94-a5e5-4868-b13c-690c73090052.png)
![image-3](https://user-images.githubusercontent.com/7606171/218609130-5ae16ca8-c2df-44f5-9004-ba4091ac57b7.png)

While I'm open to the concept and would love to give it more thought it would be nice to hear about some possible solutions to provide a more clear graph visualization. For instance, one option would be to simply only visualize the tables instead of the records.

I'd love to hear further thoughts on the matter

**Comment by unidesigner** [comment]
I'm also looking into ways for network visualization of data in surrealdb. One option may be to use [3d graphs](https://github.com/vasturiano/react-force-graph) or (compound nodes in cytoscape.js)[https://cytoscape.org/cytoscape.js-cose-bilkent/demo-compound.html].

**Comment by macjuul** [comment]
For now this feature has been implemented in the form of a new Visualizer view which allows plotting your tables and edges into a graph by using the defined schema. I might revisit the concept of visualizing individual records in the future.

**Comment by bibaswan-bhawal** [comment]
Hey, I would be more than happy to work on this feature. I need to create a graph visualizer for a project I am working on with surrealdb which I believe I could extend to be more general to graph any table. I haven't fully implemented it yet but I can create a proposal with an initial concept of how it would work to see if people would be interested in it. 

Then I can start building the feature out. However, I won't be able to start working on this for at least another two weeks so if you don't plan on working on it between then I can take it on.

**Comment by macjuul** [comment]
> Hey, I would be more than happy to work on this feature. I need to create a graph visualizer for a project I am working on with surrealdb which I believe I could extend to be more general to graph any table. I haven't fully implemented it yet but I can create a proposal with an initial concept of how it would work to see if people would be interested in it.
> 
> Then I can start building the feature out. However, I won't be able to start working on this for at least another two weeks so if you don't plan on working on it between then I can take it on.
> 
> Also if you have the code for the graph visualizer you referenced earlier then do you mind sharing it.

Great to know you're willing to continue exploring this concept. I don't have plans to work on it myself, so you're totally good to work on it when possible. It would be best if we can integrate this into the existing visualizer view in some way

While I don't have the old code anymore, the current visualizer code should come in useful. I simply pulled in and rendered all records, checking for the presence of `in` and `out` fields to detect edges.

I'm looking forward to reading the proposal when it's ready

**Comment by macjuul** [comment]
Closing due to the revised designer view replacing the original visualizer view

**Comment by macjuul** [comment]
This has now been implemented in #651
