### ISSUE TITLE
Record link has no destination

### ISSUE THREAD

**Issue by kratess** [StarlaneStudios/Surrealist#23]
**Describe the bug**
After creating a record with the surrealdb library for python as follows: surrealdb_client.create_one("table", "123", {"data": 123})
On trying to open it a popup came out and say "Record link has no destination"
When I try to read data with surreal sql cli it gives me the correct data.

**To Reproduce**
1. Create a script in python with as https://github.com/surrealdb/surrealdb.py/blob/main/examples/http_client_example.py
2. use method create_one with a numeric id

**Environment (you can view the current version under Settings):**
 - OS: Ubuntu

**Comment by macjuul** [comment]
Is this still present in the latest version of Surrealist? I have personally not been able to reproduce this issue.

**Comment by macjuul** [comment]
Closing due to lack of response
