### ISSUE TITLE
Bad font rendering on Ubuntu 22.10

### ISSUE THREAD

**Issue by unidesigner** [StarlaneStudios/Surrealist#27]
**Describe the bug**
I just installed v1.6.0 on my Ubuntu 22.10 and the rendering of text looks quite think, almost not visible. I attach a screenshot where it's hopefully visible. The text for the queries and results look just fine. It was fine in a previous release.
![Screenshot from 2023-03-03 12-44-23](https://user-images.githubusercontent.com/136799/222713444-ff5d2378-1cde-4b7a-a4f7-1b732f7211a0.png)

**Expected behavior**

**Environment (you can view the current version under Settings):**
 - OS: Ubuntu
 - Version 22.10

**Comment by unidesigner** [comment]
Just tested with the previosu 1.5.2 release.

**Comment by macjuul** [comment]
Thanks for the issue report! A fix for font rendering has been made and released in [1.6.1](https://github.com/StarlaneStudios/Surrealist/releases/tag/v1.6.1)
