### ISSUE TITLE
General UI bugs

### ISSUE THREAD

**Issue by bibaswan-bhawal** [StarlaneStudios/Surrealist#30]
**Describe the bug**
I know its very nit-picky but being a UI designer i just thought I'd point out a few UI inconsistencies. I can help fix some of these if needed.

1. the connect button does not fill the url bar on windows: 

windows: 
![2023-03-04 20_47_12-New tab - Surrealist Explorer](https://user-images.githubusercontent.com/67685395/222942411-1f839477-0cd4-45f8-b8d3-a52d84192e81.png)

Mac: 
<img width="129" alt="sec3" src="https://user-images.githubusercontent.com/67685395/222942461-5fc7f047-3c25-4e41-b248-969bd1be6488.png">

you can see there is some wierd padding on windows. looks fine on mac

2. Connect button has wrong highlight border radius:

<img width="141" alt="sec" src="https://user-images.githubusercontent.com/67685395/222942478-93a632de-cf62-4602-a7cb-1e9f664050cd.png">

if you highlight the connect button on mac the highlight as a lower border radius than the button which makes it look wierd.

3. when resizing panes on mac things seem to get highlight:

<img width="261" alt="sec2" src="https://user-images.githubusercontent.com/67685395/222942520-daa6406c-1214-4aa1-8e77-8d4dd7580809.png">

the main query mode seems fine it's all the new ones.

4. The surrealist icon is too big compared to other icons on macos:

<img width="122" alt="Screenshot 2023-03-04 at 9 03 20 PM" src="https://user-images.githubusercontent.com/67685395/222942647-0b2b539a-48b0-44eb-baa0-1ee96ee2c440.png">

**Environment (you can view the current version under Settings):**
 - OS: Windows & MacOS
 - Version 1.6.1

**Comment by bibaswan-bhawal** [comment]
For the icon I created the proper sized icon: 

![app-icon](https://user-images.githubusercontent.com/67685395/222942692-4ccd718a-8739-4916-9301-18a0a16c7a33.png)

assuming you used tauri-icon cli this should generate the right sized icons to conform with icons size guidelines for platforms.

**Comment by macjuul** [comment]
Thanks for the issue!

There were quite some formatting/indentation issues in your PR plus some unnecessary files so I decided to use your PR as reference and fixed the issues separately.

As for the icon, it appears that scaling it down does cause it to look incorrect/too small on windows. I'll perform some further testing on both windows and macos later this week to fix the icon for both platforms definitively.

I'll leave this issue open until we're satisfied with the size of the icon

Thanks!

**Comment by bibaswan-bhawal** [comment]
Hey, no worries I did a quick fix so understandable. For the icons macos uses the .icns file while windows uses the .ico so you could  use the existing .ico file and the new .icns file to keep the icons the right size on both platforms.
