### ISSUE TITLE
Connection Closed Unexpected connection close (1006)

### ISSUE THREAD

**Issue by unidesigner** [StarlaneStudios/Surrealist#33]
**Describe the bug**
I get an `Connection Closed Unexpected connection close (1006)` message if I connect to a remote instance that is secured via SSL and nginx and runs surrealdb in a docker container (nightly build). I do see the `/rpc` call in the remote console, but I do not see why the connection is closed. I can connect to the same endpoint e.g. via `surrealdb-py`. Is there a way to show additional debug information about the connection failure? I assume it's not a bug in surrealist, but some misconfiguration. It may help others to debug.

**To Reproduce**
See bug description.

**Expected behavior**
Connection works as expected.

**Environment (you can view the current version under Settings):**
 - OS: Ubuntu 22.10

**Comment by macjuul** [comment]
You can press `Ctrl + Shift + I` to open dev tools, in which you should be able to find logging output, network information, and more. I'm unsure how this looks on Ubuntu, so best is to click around and see if you notice anything that might indicate the issue.

Your setup should hypothetically work just fine, so this is definitely strange

**Comment by unidesigner** [comment]
Thank you, this is helpful with the dev console. Apparently, my nginx configuration for using websockets was wrong. I could now fix it with [those suggestions](https://stackoverflow.com/questions/12102110/nginx-to-reverse-proxy-websockets-and-enable-ssl-wss), that is, adding
```
   proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    # WebSocket support
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
```
to the nginx location block.

**Comment by macjuul** [comment]
I've run into this myself as well in the past, this is indeed the solution!
