### ISSUE TITLE
Surrealist 1.6.2 probable memory leak

### ISSUE THREAD

**Issue by devpikachu** [StarlaneStudios/Surrealist#38]
**Describe the bug**
Surrealist 1.6.2 seems to have some kind of memory leak, as it peaked at 16 gigs memory usage.
![image](https://user-images.githubusercontent.com/30475873/224547666-565a135a-702f-4787-8466-00ef8a7bfa8a.png)

**To Reproduce**
Unknown, was using the explorer at the time.

**Expected behavior**
No memory leak

**Environment (you can view the current version under Settings):**
 - OS: Fedora Linux 37 (KDE 5.27.2, KDE Frameworks 5.103.0, Qt 5.15.0, Kernel 6.1.14-200.fc37)
 - Version: 1.6.2

**Comment by macjuul** [comment]
I haven't been able to reproduce this issue, nor have I received any other mentions of this happening so far. Could you confirm whether this is still present and caused by Surrealist?

**Comment by devpikachu** [comment]
@macjuul I've not used Surrealist for a while now due to switching to a different project using a different database engine. I'd say we close this for now and in the future, if I see this happening again, I'll reopen.

Thanks for looking into this!
