### ISSUE TITLE
Bug: Designer view disappears with more than 5 relations

### ISSUE THREAD

**Issue by itsezc** [StarlaneStudios/Surrealist#381]
**Describe the bug**
When you have 5 or more tables that are "related", the designer view shows absolutely nothing, when tables are clearly present

<img width="1800" alt="image" src="https://github.com/user-attachments/assets/02e65915-bc58-434e-a5db-0c03c7007ec2">
<img width="1800" alt="image" src="https://github.com/user-attachments/assets/fb295fdc-2af4-42fb-9184-daef1ef1f5a7">

**To Reproduce**
Create 4 normal or more tables that are related with "edges" / relations between them

**Expected behavior**
Display tables displayed as they would be otherwise expected to.

**Environment:**
```
Version: 2.1.6
Flags: feature_flags: true, models_view: true, apidocs_view: true, themes: true, newsfeed: true, database_version_check: false, highlight_tool: false, surreal_compat: v2, changelog: auto
```

**Comment by macjuul** [comment]
This is usually caused due to a mistake in the schema, such as referencing incorrect table names within relation IN/OUT fields. I'll improve the error correction within Surrealist to prevent the entire graph from crashing, and possibly reporting on invalid schema values
