### ISSUE TITLE
Scoop or Chocolatey support

### ISSUE THREAD

**Issue by stevefan1999-personal** [StarlaneStudios/Surrealist#42]
**Describe your feature request**

I want to `scoop install surrealist` or `cinst surrealist` so I can keep my software manifest clean and reproducible

**Are you willing to contribute this feature?**
I don't know how to make the package manifests, but I am willing to learn to do so.

**Comment by DcZipPL** [comment]
Surrealist is already in winget-pkg repository. I don't think that adding this app to multiple package managers is good idea.

**Comment by macjuul** [comment]
As @DcZipPL mentioned surrealist is available in WinGet, I plan on mentioning it in the documentation soon
