### ISSUE TITLE
Record Selection

### ISSUE THREAD

**Issue by ntorrey** [StarlaneStudios/Surrealist#43]
**Describe your feature request**
Currently, in the "Record Explorer" view, I have to click on the record _id_ in order to display the record in the "Inspector". It would be nice if I were able to select the record by clicking anywhere in the row. This would especially be helpful if there are many fields: If I am scrolled far to the right (horizontally), then I have to scroll all the way back to the beginning in order to select a record for editing.

**Are you willing to contribute this feature?**
Not capable!

**Comment by macjuul** [comment]
I actually have a new update going live tomorrow adding exactly this functionality :)

Thanks for the suggestion regardless!

**Comment by ntorrey** [comment]
@macjuul Wow, how providential! Looking forward to the update!
