### ISSUE TITLE
Can't do scope authentication

### ISSUE THREAD

**Issue by SorenHolstHansen** [StarlaneStudios/Surrealist#44]
This is probably not an issue with surrealist, but I have tried for a long time, and hope you can solve my issue.

I have defined a database scope called `user_scope` with a signup query: `CREATE user SET email = $email, pass = crypto::argon2::generate($pass)` and signin query `SELECT * FROM user WHERE email = $email AND crypto::argon2::compare(pass, $pass)` with 12h session duration.

However when trying to do scope authentication in the connection details like this
<img width="654" alt="Screenshot 2023-04-04 at 22 20 17" src="https://user-images.githubusercontent.com/54755687/229911277-42448f99-79a5-426c-a74c-3e3ae784396b.png">
<img width="586" alt="Screenshot 2023-04-04 at 22 20 22" src="https://user-images.githubusercontent.com/54755687/229911291-87eb4263-46c8-4231-a39b-46de3cabf616.png">

It still says I am offline, and the only thing logged in the terminal is `2023-04-04T20:21:19.537330Z INFO surrealdb::net: 127.0.0.1:65491 GET /rpc HTTP/1.1 101 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)" 136.791µs`

What am I doing wrong?

**Comment by macjuul** [comment]
Strange, I recreated your example and it is working successfully on my side (Running SurrealDB beta 9)

I'm not entirely sure what the problem could be. Are you sure a valid user account is present in the database before making the connection? Surrealist only authenticates and doesn't register
