### ISSUE TITLE
latest version still causes surreal beta 9 to crash

### ISSUE THREAD

**Issue by keeganstothert** [StarlaneStudios/Surrealist#47]
using surreal beta 9 and surrealist 1.6.4 I am still gettings this error when attempting to connect.

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax("invalid type: sequence, expected a string")', lib/src/sql/statements/define.rs:1009:72
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    8996 abort      surreal start --user root --pass root --log debug -- file:Database/
```

I'm also still having to run a separate instance of surreal in the cli because of this error
![image](https://user-images.githubusercontent.com/3612936/231017181-f302bf67-ada0-4be1-800d-7a7d087ccd1a.png)

MacOS 13.3.1
surreal 1.0.0-beta.9+20230402.5eafebd
surrealist 1.6.4

**Comment by keeganstothert** [comment]
![Screenshot 2023-04-10 at 5 22 18 PM](https://user-images.githubusercontent.com/3612936/231017507-a2b9925b-4b06-4766-a55b-e7e2d46d91d2.png)
![image](https://user-images.githubusercontent.com/3612936/231017534-60979ba1-3773-425f-b356-4c7e7dfd6e0f.png)

connection config

**Comment by macjuul** [comment]
This seems like a SurrealDB error to me, could you ask surreal developers about this perhaps?
