### ISSUE TITLE
Editable records returned from queries 

### ISSUE THREAD

**Issue by ntorrey** [StarlaneStudios/Surrealist#48]
**Describe your feature request**
I suppose this one is tricky, but I often find myself wanting to query data, and then edit that data in place. I understand why the results in the query editor are read-only, but I thought of two possible ways around this:

1. Highlight the 'id' field (if returned in the query) in such a way that it is clickable and will open an 'editable' record window.
2. Make the 'Explorer' View queryable with 'WHERE' statements somehow.

**Are you willing to contribute this feature?**
I can't...

**Comment by macjuul** [comment]
Thanks for your suggestion! For now I've decided to implement your second suggestion and implemented a new button to toggle a filter input in the explorer view

![image](https://user-images.githubusercontent.com/7606171/233963737-f5cf2a10-11bc-444c-862f-48b0814eb303.png)

I'll continue to consider implementing your first suggestion as well however it would be more complex, so hopefully this is sufficient for now

**Comment by ntorrey** [comment]
Awesome! Looking forward to the next release!
