### ISSUE TITLE
creating a record with a variable shows result as null

### ISSUE THREAD

**Issue by leefordjudes** [StarlaneStudios/Surrealist#49]
**Describe the bug**
While creating a record with a variable, it doesn't show the result, instead, it shows null, but the record created,
and record explorer is not automatically refreshed, it requires manual refresh

**To Reproduce**
1. use surrealist 1.7
2. simply create the record like in the image below

**Expected behavior**
Show Record

**Environment (you can view the current version under Settings):**
 - OS: Windows
 - Version 10

![image](https://user-images.githubusercontent.com/13608248/236372262-6e885735-8795-40a4-848a-8c5df400e83a.png)

**Comment by leefordjudes** [comment]
is there any possible to use a variable to create id

**Comment by macjuul** [comment]
`LET` queries themselves don't return anything. You will have to switch to the appropriate query first (In your case the third one) by using the pagination underneath the response json

**Comment by leefordjudes** [comment]
kindly first try this in the desktop version of Surrealist 1.7
![image](https://user-images.githubusercontent.com/13608248/236516646-c7d418f8-86c8-40fb-97f1-564b693bb2b4.png)

**Comment by macjuul** [comment]
Selecting the second tab in the result panel should display the result of the create query

**Comment by leefordjudes** [comment]
yes, but it displays null as a result., but the record is saved, and it can be viewed by the record explorer

**Comment by macjuul** [comment]
It's working for me when switching to the second tab
![image](https://user-images.githubusercontent.com/7606171/236612819-af62b8b9-4e31-4eed-b8b2-bd311ed550f0.png)

Since its working on my end there's nothing really for me to fix, however I'll keep this issue open in case others run into this

**Comment by leefordjudes** [comment]
yes, it's working for me too, in the previous version all results are shown as tabs, so, I missed it.
Thank you.
