### ISSUE TITLE
Accessing array elements using index variable, shows parse error on index variable

### ISSUE THREAD

**Issue by leefordjudes** [StarlaneStudios/Surrealist#51]
**Describe the bug**
Accessing array elements using index variable, shows parse error on index variable.

**To Reproduce**
1. create variables and record them as below image, I gave hardcoded values for id and array index, it's working
![image](https://user-images.githubusercontent.com/13608248/236721490-cde6a1fd-263d-406c-a5e4-91bb9ebbaab5.png)

2.create record, and assign value for id using variable, and hardcoded value for index - its also working.
![image](https://user-images.githubusercontent.com/13608248/236721757-31fe9b59-4512-47ee-9c98-d74cddcf9890.png)

3.list all records are good.
![image](https://user-images.githubusercontent.com/13608248/236722008-a9027f00-6389-488f-ae6d-7ac596f87776.png)

4.create record, and assign value for id using variable, and access array element using index variable shows parse error.
![image](https://user-images.githubusercontent.com/13608248/236722127-d881c28f-2283-435b-ab19-0646ac442edb.png)

**Expected behavior**
record should created.

**Environment (you can view the current version under Settings):**
 - OS: Windows
 - OS Version 10
 - Surreal Version: beta9
 - Surrealist Version: 1.7.0

**Comment by macjuul** [comment]
At first glance I don't believe these are Surrealist issues. Keep in mind Surrealist is just a graphical GUI for SurrealDB, any and all query logic and parse errors are returned from the database

Can you test if this behavior is consistent with `surreal sql`?

**Comment by leefordjudes** [comment]
this is an issue from Surrealdb,
issue - https://github.com/surrealdb/surrealdb/issues/1910
