### ISSUE TITLE
Strange display

### ISSUE THREAD

**Issue by kratess** [StarlaneStudios/Surrealist#53]
**Describe the bug**
![image](https://github.com/StarlaneStudios/Surrealist/assets/34928009/b756a908-d59d-4549-b522-984773fa3265)

**To Reproduce**
I don't know how this ended up but I noticed it in the database.

**Environment (you can view the current version under Settings):**
 - OS: Windows
 - Version 1.5.2

**Comment by macjuul** [comment]
This was an issue in older versions of Surrealist, it should be working correctly in the latest version
