### ISSUE TITLE
Can't select empty record in explorer view

### ISSUE THREAD

**Issue by DcZipPL** [StarlaneStudios/Surrealist#54]
**Describe the bug**
It is not possible to select record in explorer view that has empty id.

![image](https://github.com/StarlaneStudios/Surrealist/assets/31044091/5f8a6abb-9697-4c59-ab97-e01baeb00fe7)

**To Reproduce**
1. Go to explorer view
2. Create simple record with non empty id
3. Create record with empty id `{"id": ""}`
4. Try to select other record and try select this record
5. Can't open inspector on this record

**Expected behavior**
You can select a record with empty id and inspector opens.

**Environment (you can view the current version under Settings):**
 - OS: EndeavourOS (Linux) and Windows
 - Version: 1.7.1

**Comment by macjuul** [comment]
While it is fixable, it seems SurrealDB itself also struggles with records without id as they cannot be directly queried using `SELECT` causing further issues, so I'll leave the behavior as is for now until SurrealDB makes changes in this area
