### ISSUE TITLE
Red error line shows in multiline (with enter) SQL commands, long line (without enter) wont show an error.

### ISSUE THREAD

**Issue by leefordjudes** [StarlaneStudios/Surrealist#57]
**Describe the bug**
red error line shows in multiline SQL commands.
Long-line SQL commands won't show an error.

**To Reproduce**
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/69091a7d-0d2d-4f99-a988-4049f86ddd1a)
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/de3436dc-684d-4693-ba47-30b177a22200)

if I move to another tab, and reopen this tab, then it won't show the error line,
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/577c7bb5-28b8-40ac-a1c1-e2be50f80c7d)

after that, if I type anything in the current tab (which have multiline command), then immediately it shows an error line
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/04a9d356-3874-4164-a595-a8c2bcca0e1d)

**Expected behavior**
Don't show an error line.

**Environment (you can view the current version under Settings):**
 - OS: Windows
 - Version 10
 - surrealist: 1.7.1

**Comment by macjuul** [comment]
Sorry for the wait, this issue will be fixed in the next release as I have revised the error highlighting logic
