### ISSUE TITLE
keyboard shortcut ctrl+/ wont work in version 1.7.1, need keyboard shortcut for comment 

### ISSUE THREAD

**Issue by leefordjudes** [StarlaneStudios/Surrealist#58]
**Describe the bug**
keyboard shortcut ctrl+/ wont work, need keyboard shortcut for comment 

**To Reproduce**
simply type some commands and comment using ctrl+/
it wont work.

**Expected behavior**
it must comment, comment worked on previous version 1.7.0

**Environment (you can view the current version under Settings):**
 - OS: windows
 - Version 10
 - surrealist: 1.7.1

**Comment by macjuul** [comment]
Thanks for reporting this issue! My apologies for the inconvenience. I'm currently away however I'll look into this issue as soon as I'm available again in roughly a week to two weeks from now.

If these issues are too distracting it should be safe to run an older version of Surrealist until then

**Comment by leefordjudes** [comment]
kindly check the commit, whether all your changes are committed or not, because version 1.7.1
https://github.com/StarlaneStudios/Surrealist/commit/6147152857193e422d1d02b03659fcbf5349ba77
has only version change in package.json.
https://github.com/StarlaneStudios/Surrealist/commit/c13146fd8b6e436060c4c3f08a781c64e0ad8485 is the commit for the previous version 1.7.0.

so, kindly check it.

**Comment by macjuul** [comment]
This is likely a logical issue unrelated to the versioning. I already have a few ideas on what could have caused this

**Comment by macjuul** [comment]
This issue should be fixed in the next release, together with significant improvements to the error highlighting

**Comment by ItsMateo** [comment]
Hey there! I wanted to update this issue with some new information. We are still unaware of what is causing ctrl + / to not work. However a temporary workaround, at least in the newest release [v1.7.2](https://github.com/StarlaneStudios/Surrealist/releases/tag/v1.7.2), seems to be using ctrl + ' instead.

**Comment by leefordjudes** [comment]
Ok. Thank you,
