### ISSUE TITLE
visualizer: get the edges on !

### ISSUE THREAD

**Issue by coutouly** [StarlaneStudios/Surrealist#59]
**How te get the edges shows on the visualizer**
i put somme data in surrealdb nodes and edges but never has a edge on it

**To Reproduce**

1. put some data in surrealdb with create for the two first and with relate for the third

{
    "id": "location:361820060G10",
    "location": {
        "type": "Point",
        "coordinates": [
            1.39016,
            46.439829
        ]
    },
    "properties": {
        "ID": "361820060G10",
        "cp": 36170,
        "numero": "10",
        "plan": "C+O",
        "rue": "Rue Émile Surun",
        "ville": "Saint-Benoît-du-Sault"
    },
    "type": "adresse"
}
and
{
    "id": "location:361820025U5",
    "location": {
        "type": "Point",
        "coordinates": [
            1.391046,
            46.439565
        ]
    },
    "properties": {
        "ID": "361820025U5",
        "cp": 36170,
        "numero": "5",
        "plan": "C+O",
        "rue": "Rue Belle Rampe",
        "ville": "Saint-Benoît-du-Sault"
    },
    "type": "adresse"
}
and

{
    "bbox": [
        "1.390189",
        "46.439533",
        "1.391009",
        "46.439864"
    ],
    "distance": "73.9",
    "duration": "1.1083333333333334",
    "end": "1.391009,46.439533",
   "start": "1.390189,46.439864"
}

3. in designer :
set fields:
in is record
out is record
the field type exist but i dont know what to do whith it ?
table direction is becoming an edge
4. in visualizer
error: only show location without edges.

**Expected behavior**
i want to see the edge in the visualiser. what am i missing ? in the designer ?
thanks

**Environment (you can view the current version under Settings):**
 linux with 1.7.1

**Comment by macjuul** [comment]
Hey! This issue should be fixed in the next release. It was caused by a recent change made in SurrealDB's query syntax.

As long as you define the `in` and `out` fields with the correct record types the Visualiser view should work

**Comment by coutouly** [comment]
is it possible to test it actualy ? when next release will be available ? 
thanks

**Comment by macjuul** [comment]
Should be available within a few hours! I'll reply on this issue once it is

**Comment by coutouly** [comment]
hello,
I am desapointed , it doesn' t show the edges on the graph visualiser only nodes...
could you send me an example that work ?
thank you

**Comment by coutouly** [comment]
so i succeed
![snapshot](https://github.com/StarlaneStudios/Surrealist/assets/7043117/c997459a-636e-43da-bb68-994e2c00c4b7)

**Comment by Dzordzu** [comment]
For onlookers:

In order to make it work the relation table requires defined fields. For example

```
DEFINE FIELD in ON TABLE lives TYPE record (User);
DEFINE FIELD out ON TABLE lives TYPE record (Place);
```
