### ISSUE TITLE
Font size affects caret position

### ISSUE THREAD

**Issue by darcome** [StarlaneStudios/Surrealist#60]
**Describe the bug**
A font size set in windows different than 100% causes the caret to not show the correct position.

**Environment (you can view the current version under Settings):**
 - OS: [e.g. Windows] Windows
 - Version [e.g. 1.2.0] 11

Here is a screenshot of what I mean:

![image](https://github.com/StarlaneStudios/Surrealist/assets/18150093/20aa3873-2324-4fa8-b0c0-dac83704868a)

As you can see, I have pressed the END key on the keyboard, but nonetheless the caret is not shown at the end of the query.

**Comment by ItsMateo** [comment]
Hey there! I was unfortunately unable to recreate this issue on Windows 11 with Surrealist v1.7.2. Could you please provide further instructions on how you were able to achieve this bug and track down that it was due to font size in particular?

**Comment by darcome** [comment]
How can I get the 1.7.2 version? Here on github I can only see 1.7.1

**Comment by ItsMateo** [comment]
My bad. I was using an unreleased version. It has now been released though.

**Comment by darcome** [comment]
I can confirm that with 1.7.2 the caret goes to the end of the line.

Thank you!
