### ISSUE TITLE
getting it to work on my mac

### ISSUE THREAD

**Issue by hmudge1** [StarlaneStudios/Surrealist#61]
**Describe the bug**
A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.

i follow all the step there is on there and it says this back to me
 
<img width="795" alt="Screenshot 2023-06-08 at 19 15 34" src="https://github.com/StarlaneStudios/Surrealist/assets/81761861/3cc087fc-3785-4468-bd30-2e27b0dc63a1">

"  xattr: No such file: Surrealist.app"

it in my application but it keep saying that and i cant get it to work

**To Reproduce**

how it shown on github 

**Expected behavior**

**Environment (you can view the current version under Settings):**
 - OS: Mac OS
 - Version [e.g. 1.2.0]

**Comment by macjuul** [comment]
If I'm correct this issue was discussed further and solved in the Discord, so I'll close this for now
