### ISSUE TITLE
Explorer & Designer not working

### ISSUE THREAD

**Issue by leefordjudes** [StarlaneStudios/Surrealist#62]
**Describe the bug**
Explorer & Designer do not work

**To Reproduce**
1. I have two tables, test & tbl1, it is shown below

![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/296544ba-00bb-49cd-b608-b4671734946d)
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/da9f4527-dac2-4a7f-98e9-dbdd4eb0afa7)

2. when i open explorer, it wont show any tables, and in the designer if i create one using '+' symbol, immediately it closes, and not showing the field creation.
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/697912ef-6171-42d3-8cfc-a442326994be)
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/d566eb42-e123-4721-aae0-2ad600d00dd0)

**Expected behavior**
need to show the explorer & designer to create tables and fields graphically.
and also check visualizer.

**Environment (you can view the current version under Settings):**
 - OS: windows 11
 - Version: surrealist 1.7.2

**Comment by myrkvi** [comment]
I'm having the same issue on macOS with M2. Versions 1.7.2 and 1.7.1. Database server is a remote one hosted via Fly.

**Comment by macjuul** [comment]
@leefordjudes @myrkvi Could it be that you are running SurrealDB nightly?

**Comment by myrkvi** [comment]
@macjuul: No, I'm running the `surrealdb/surrealdb:latest` Docker image.

**Comment by leefordjudes** [comment]
> @leefordjudes @myrkvi Could it be that you are running SurrealDB nightly?

yes, i am running nightly version 
1.0.0-beta.9+20230612.5c07a7b

**Comment by myrkvi** [comment]
Talked it over on the Discord server. The issue for me was that a table had a defined field of the type `record()`, which works with the version of SurrealDB on the server, but not for the local one that is running embedded in Surrealist. I.e. the syntax for that type has since changed.

Thank you, @macjuul! :)

**Comment by macjuul** [comment]
> > @leefordjudes @myrkvi Could it be that you are running SurrealDB nightly?
> 
> yes, i am running nightly version 1.0.0-beta.9+20230612.5c07a7b

There's been a recent breaking change in SurrealDB nightly which has broken compatibility with Surrealist. Theres currently a [patch version](https://github.com/bibaswan-bhawal/Surrealist/tree/v1.7.2-temp) made by @bibaswan-bhawal which is compatible with nightly.

I'll see if its possible to support both ways and might include it in the next release if possible.

**Comment by bibaswan-bhawal** [comment]
It might be possible if we query the DB version and conditonally pick the key names

**Comment by macjuul** [comment]
> It might be possible if we query the DB version and conditonally pick the key names

If I'm not mistaken it could be as simple as e.g. `info.tables || info.tb`, however I haven't had much time to look at your fork yet so I might be wrong
