### ISSUE TITLE
tokens not switched between sessions and environments

### ISSUE THREAD

**Issue by leefordjudes** [StarlaneStudios/Surrealist#63]
**Describe the bug**
tokens not switched between sessions and environments

**To Reproduce**
1. run two instance of surreal db with different ports eg: 5000, 8000
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/fa87320b-baa6-40d1-9b9d-7b762c292e11)

2. create session "local-admin" on port 5000 with username admin & password admin & create table west and records on 
   db: "westdb"  namespace: "dbs"
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/9fa3913a-f68a-4ae3-94cd-079d3868b9c5)
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/5e879863-0dbb-45bf-991c-93ca9d8d47a6)

3. 2. create session "local-root" on port 8000 with username root & password root & create table east and records on 
   db: "eastdb"  namespace: "dbs"
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/c6901642-8f84-426e-b2a3-59ff542dca9d)
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/9dac65b1-ea0e-49cf-9afb-9b0222d84ec2)

4. now switch tab session "local-admin", and select tables from local-root session tables
![image](https://github.com/StarlaneStudios/Surrealist/assets/13608248/0f5101be-7b36-4a5d-8d27-7dbc5dbba902)

see the amazing results, we are taking data from other namespace & db,
this is may be you are not switching the tokens & urls.
kindly check it. and resolve it.

the above also not work for scope change

**Expected behavior**
data should not come from other dbs and namespace.

**Environment (you can view the current version under Settings):**
 - OS: Windows
 - Version 1.7.2
 - SurrealDB 1.0.0-beta.9+20230612.5c07a7b

**Comment by macjuul** [comment]
I have observed this behavior myself as well, I'll look into it for the next release

**Comment by leefordjudes** [comment]
kindly anyone resolve this UI-related issue. this also arises for scope change.

**Comment by macjuul** [comment]
This appears to be working correctly on the latest version of main
