### ISSUE TITLE
AppImage is incompatible with RHEL9.

### ISSUE THREAD

**Issue by mskarbek** [StarlaneStudios/Surrealist#69]
**Describe the bug**
AppImage fails to start.

**To Reproduce**
```
marcin@ishikawa ~/downloads> chmod 0755 surrealist-v1.7.4-linux.AppImage 
marcin@ishikawa ~/downloads> ./surrealist-v1.7.4-linux.AppImage 
surrealist: /lib64/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/.mount_surreaDmV95t/usr/lib/libwebkit2gtk-4.0.so.37)
surrealist: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /tmp/.mount_surreaDmV95t/usr/lib/libjavascriptcoregtk-4.0.so.18)
```

**Expected behavior**
Surrealist starts.

**Environment (you can view the current version under Settings):**
 - Operating System [e.g. Windows]: Red Hat Enterprise Linux 9.2
 - Surrealist Version [e.g. 1.2.0]: 1.7.4
 - SurrealDB Version [execute "surreal version"]: 1.0.0-beta.9+20230402.5eafebd for linux on x86_64

**Comment by macjuul** [comment]
This appears to be related to the version of `glibc` installed on your system. I'm not familiar with your linux distro so there's not much I can help with I'm afraid

**Comment by mskarbek** [comment]
Yes, you can help, just bundle glibc during appimage build or lower glibc version requirement.

**Comment by macjuul** [comment]
The Linux build process is mostly out of my scope so any PR on this matter would be welcome
