### ISSUE TITLE
Unable to unzoom

### ISSUE THREAD

**Issue by SamuelMorel** [StarlaneStudios/Surrealist#73]
**Describe the bug**
I'm unable to unzoom using the ctrl + "-" shortcut. 

**To Reproduce**
1. From the UI
2. Press ctrl + "=" (Zoom in)
3. Press ctrl + "-" (Does nothing)

**Expected behavior**
This shortcut (or another) must be available to unzoom/reset zoom.

**Environment (you can view the current version under Settings):**
 - Operating System [e.g. Windows]: Windows 
 - Surrealist Version [e.g. 1.2.0]: 1.7.4
 - SurrealDB Version [execute "surreal version"]: v1.0.0-beta.9

**Comment by macjuul** [comment]
Zooming has been removed in version 1.7.5 due to multiple issues it caused, you can read more about this [here](https://github.com/StarlaneStudios/Surrealist/issues/78#issuecomment-1657286813). We intend to bring back zooming once we can implement it properly
