### ISSUE TITLE
Incorrect result for integer near max value

### ISSUE THREAD

**Issue by Odonno** [StarlaneStudios/Surrealist#74]
**Describe the bug**

When setting value for the max value (u64) = 9223372036854775807, it returns an incorrect value = 9223372036854776000

It works fine for all other scenarios:

* zero (0)
* min (-9223372036854775808)
* non large integer

I can reproduce this error both on beta-9 and nightly

**To Reproduce**

Try this code:

```sql
CREATE number SET name = '9223372036854775807', value = 9223372036854775807;

SELECT * FROM number;
```

It will display this:

```json
[
    {
        "id": "number:v2jlfztewmcz0yx0ap4v",
        "name": "9223372036854775807",
        "value": 9223372036854776000
    }
]
```

**Expected behavior**

Return the correct value

**Environment (you can view the current version under Settings):**
 - Operating System [e.g. Windows]: Windows
 - Surrealist Version [e.g. 1.2.0]: 1.7.4
 - SurrealDB Version [execute "surreal version"]: 1.0.0-beta.9+20230402.5eafebd for linux on x86_64

**Comment by macjuul** [comment]
This is likely related to how JavaScript treats numbers, specifically 64 bit numbers not being supported. I'm not currently aware of a fix/workaround for this issue I'm afraid

**Comment by Odonno** [comment]
Maybe https://mikemcl.github.io/bignumber.js/

```js
const x = new BigNumber("9223372036854775807");
```
