### ISSUE TITLE
Wrong error: Surreal executable not found. Make sure the SurrealDB CLI is available in the command line.

### ISSUE THREAD

**Issue by gander** [StarlaneStudios/Surrealist#76]
**Describe the bug**
There are various causes of errors, program file missing, ports occupied, permissions missing, so it would be nice if these errors had separate error messages rather than being misleading as to the cause of the problem.

![image](https://github.com/StarlaneStudios/Surrealist/assets/421597/6ef4a043-5046-4288-98bb-8f5e30799e94)

![image](https://github.com/StarlaneStudios/Surrealist/assets/421597/4b4c7a9a-e569-43fa-a0a2-58181f046f44)

**To Reproduce**
1. Install app
2. Run something on port 8000
3. Run app with default settings
4. Click start local database
5. See error "Surreal executable not found. Make sure the SurrealDB CLI is available in the command line."

**Expected behavior**
Display error message like "Error creating server: Address 8000 already in use".

**Environment (you can view the current version under Settings):**
 - Operating System: `Linux Mint 21.2 Victoria`
 - Surrealist Version: `1.7.4`
 - SurrealDB Version: `1.0.0-beta.9+20230402.5eafebd for linux on x86_64`

**Comment by macjuul** [comment]
While I can't detect the actual reason Surreal fails to launch, I have rephrased the alert and made the console tab available at all times, allowing you to view the output and diagnose the problem manually

![image](https://github.com/StarlaneStudios/Surrealist/assets/7606171/0837118c-5ee3-4f57-b31c-50809a4cbeda)
