### ISSUE TITLE
Use command key as control key (macOS)

### ISSUE THREAD

**Issue by kearfy** [StarlaneStudios/Surrealist#77]
**Describe your feature request**
Currently, when you want to zoom in or out on macos, you need to use the CTRL key as the control key. This is not intuitive, as on macos, the Command key is usually used for this. 
This is only an issue in the desktop app, as the zoom level is controlled by the browser in the case of the web app :)

**Are you willing to contribute this feature?**
No

**Related pull request (if applicable)**
N/A

**Comment by jackson-bean** [comment]
Since zooming will likely be removed soon (see https://github.com/StarlaneStudios/Surrealist/issues/78#issuecomment-1657286813), I'm going to close this and shelve it for when it might be relevant.

**Comment by kearfy** [comment]
Yep! Sounds good!
