### ISSUE TITLE
Zooming in/out dispositions the cursor from the actual text

### ISSUE THREAD

**Issue by kearfy** [StarlaneStudios/Surrealist#78]
**Describe the bug**
Zooming in/out dispositions the cursor from the actual text. At the normal 100% scale it is fine, and this is also not an issue on the web. Just on the desktop app.

**To Reproduce**
1. Open Surrealist
2. Zoom in or out a bit
3. Notice how the cursor is at a different position as the actual text you are trying to edit

**Expected behavior**
For the cursor to be at the same position as the text you're editing

**Environment (you can view the current version under Settings):**
 - Operating System [e.g. Windows]: macOS
 - Surrealist Version [e.g. 1.2.0]: 13.4.1 (Ventura)
 - SurrealDB Version [execute "surreal version"]: `1.0.0-beta.9+20230723.432a6cc for macos on aarch64`

**Comment by jackson-bean** [comment]
Thanks for opening an issue! Zooming isn't natively supported by Tauri at the moment (see https://github.com/tauri-apps/tauri/issues/3310), so we've had to come up with a workaround. Obviously this is causing more issues than it fixes, so unless there is another workaround we haven't considered, we'll probably have to remove zooming for the time being.

**Comment by kearfy** [comment]
I see! Makes sense :)
Thanks for the fast response!
