### ISSUE TITLE
Cursor blips to end of editor for last two "groups" of queries

### ISSUE THREAD

**Issue by kearfy** [StarlaneStudios/Surrealist#79]
**Describe the bug**
When trying to click any text in the last two groups of queries in the left pane editor, the editing cursor will move to the end of the editor. This is only an issue in the desktop app, the web app is fine

**To Reproduce**
1. Open Surrealist (desktop app)
2. Paste the following snippet in the left pane editor:
```sql
-- Fine here

-- Also fine

-- But when trying to select text from the whiteline above (line 4), and then anything below that

-- The cursor will always end up at the end of this line
```
3. Try to select text as described by the comments
4. If this does not trigger the bug, try zooming in/out first, then back to the normal 100%. I have a feeling this might be related to #78.

**Expected behavior**
I would expect to be able to select any text I want throughout the whole editor.

**Environment (you can view the current version under Settings):**
 - Operating System [e.g. Windows]: macOS
 - Surrealist Version [e.g. 1.2.0]: 13.4.1 (Ventura)
 - SurrealDB Version [execute "surreal version"]: `1.0.0-beta.9+20230723.432a6cc for macos on aarch64`

**Comment by macjuul** [comment]
Fixed in the next release
