### ISSUE TITLE
Allow to specify path

### ISSUE THREAD

**Issue by prabirshrestha** [StarlaneStudios/Surrealist#8]
**Describe your feature request**
I use rocksdb as surrealdb backend so would be good if we can specify optional path when starting the surrealdb server.

```bash
surreal start -u root -p root -s file:///home/prabir/app/path_to.db
```

**Are you willing to contribute this feature?**
No

**Comment by prabirshrestha** [comment]
Seems like works already.

**Comment by macjuul** [comment]
Hey, this is already possible by changing the local database storage on the settings screen. You'll be able to input a path once selected

**Comment by prabirshrestha** [comment]
I can see it now. Thanks.
