### ISSUE TITLE
Connect through Proxy

### ISSUE THREAD

**Issue by abegehr** [StarlaneStudios/Surrealist#80]
**Describe your feature request**
It would be great to be able to connect to a SurrealDB instance through a proxy directly from the Surrealist app, therefore you could directly connect with your database even if it's in a VPN somewhere only accessible through a local proxy. 

**Are you willing to contribute this feature?**
Yes

**Related pull request (if applicable)**
n/a

**Comment by macjuul** [comment]
Sounds interesting, could you give a more detailed explanation of how you would imagine this working?
