### ISSUE TITLE
Explorer / Designer not showing data for a specific db.

### ISSUE THREAD

**Issue by andreinistor** [StarlaneStudios/Surrealist#89]
**Describe the bug**
Explorer and Designer tabs stopped showing data.
This happens for only one database.
If there Is a way to see logs, I could attach them.

**To Reproduce**
I haven't found a way to reproduce the issue.
Tried another NS with the same DB name.
Tried another DB in the same NS.
Tried copying the same define statements from the problematic DB and applying them to a new DB.
This bug seemed to appear when switching to 1.7.5, but still persisted when switching back to 1.7.4.

What seems to partially work:
Add a new NS (NS2) with the same DB name (dev) and the same tables (with no content). Switch to this DB and the tables are now visible.
Change connection details to the problematic DB, now the tables are visible, including the content when clicking on them (in Explorer, but not in Designer).

**Expected behavior**
Being able to use Designed and Explorer tabs.

**Environment (you can view the current version under Settings):**
 - Operating System [e.g. Windows]:  MacOS, Ventura 13.0.1
 - Surrealist Version [e.g. 1.2.0]:  1.7.4 / 1.7.5
 - SurrealDB Version [execute "surreal version"]: 1.0.0-beta.9+20230402.5eafebd for macos on x86_64

**Comment by macjuul** [comment]
Is this issue still present in the latest release?
