### ISSUE TITLE
Add aur package for archlinux

### ISSUE THREAD

**Issue by prabirshrestha** [StarlaneStudios/Surrealist#9]
Need to add [webkit2gtk](https://archlinux.org/packages/extra/x86_64/webkit2gtk/) as deps then create `surrealist-bin` package in [aur](https://aur.archlinux.org/).

Can use https://github.com/marketplace/actions/publish-aur-package

**Comment by tacheometry** [comment]
I've published a package, https://aur.archlinux.org/packages/surrealist-bin. It uses the `.deb` file.

**Comment by macjuul** [comment]
> I've published a package, https://aur.archlinux.org/packages/surrealist-bin. It uses the `.deb` file.

Thanks a lot for that! ❤️

@tacheometry My apologies for not knowing much about this, will this be kept up to date with the latest version?

I'll close this issue as resolved for now
