### ISSUE TITLE
Feature: view raw output of query

### ISSUE THREAD

**Issue by kearfy** [StarlaneStudios/Surrealist#91]
**Describe your feature request**
Would be a nice feature besides the current JSON and table view to also get a JSON editor with the raw output (well, not the entire message, but the raw result of the message)

**Are you willing to contribute this feature?**
Potentially

**Related pull request (if applicable)**
N/A

**Comment by macjuul** [comment]
Due to a change in how connections are made as of the nightly branch this won't be possible anymore unfortunately
