### ISSUE TITLE
Query and Variable sections just display the message "Loading..."

### ISSUE THREAD

**Issue by agfp** [StarlaneStudios/Surrealist#96]
**Describe the bug**
The "Query" and "Variable" sections aren't loading. Screenshot: https://ibb.co/7gf5F36

After `CTRL+SHIFT+I` I can see two "Unacceptable TLS certificate" errors, one for `https://cdn.jsdelivr.net/npm/monaco-editor@0.36.1/min/vs/loader.js` and another one for `https://api.github.com/repos/StarlaneStudios/Surrealist/releases/latest`. 

Googling around, this seems to be a Tauri issue, that happens with multiple distros. No solution found.

EDIT: When I compile it myself the problem go away. 

**To Reproduce**
1. Do a brand new OpenSuse Tumbleweed install
2. Run Surrealist appimage

**Expected behavior**
Query and Variable sections to load

**Environment (you can view the current version under Settings):**
 - Operating System: OpenSuse Tumbleweed, brand new install
 - Surrealist Version: 1.8.0
 - SurrealDB Version:  1.0.0-beta.9+20230402.5eafebd

**Comment by koakh** [comment]
I **confirm the same error** as @agfp in my OpenSuse Tumbleweed with AppImage

my solution is the same as @agfp,
I checkout and build and now it works very well

thanks for the tip @agfp

great work, this Tauri app is awesome

**Comment by macjuul** [comment]
Is this issue still present on the latest version?

**Comment by agfp** [comment]
Fixed.
